/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "AdmobAds_autodefs.h"
#include "s3eEdk.h"
#include "AdmobAds.h"
//Declarations of Init and Term functions
extern s3eResult AdmobAdsInit();
extern void AdmobAdsTerminate();


#if defined I3D_OS_IPHONE || defined I3D_OS_OSX

static s3eResult AdmobAds_InitAds_wrap(const char* pub_id, int ad_type, int orientation, int x, int y)
{
    IwTrace(ADMOBADS_VERBOSE, ("calling AdmobAds func on main thread: AdmobAds_InitAds"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)AdmobAds_InitAds, 5, pub_id, ad_type, orientation, x, y);
}

static s3eResult AdmobAds_ShowAds_wrap()
{
    IwTrace(ADMOBADS_VERBOSE, ("calling AdmobAds func on main thread: AdmobAds_ShowAds"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)AdmobAds_ShowAds, 0);
}

static s3eResult AdmobAds_HideAds_wrap()
{
    IwTrace(ADMOBADS_VERBOSE, ("calling AdmobAds func on main thread: AdmobAds_HideAds"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)AdmobAds_HideAds, 0);
}

static s3eResult AdmobAds_Move_wrap(int orientation, int x, int y)
{
    IwTrace(ADMOBADS_VERBOSE, ("calling AdmobAds func on main thread: AdmobAds_Move"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)AdmobAds_Move, 3, orientation, x, y);
}

#define AdmobAds_InitAds AdmobAds_InitAds_wrap
#define AdmobAds_ShowAds AdmobAds_ShowAds_wrap
#define AdmobAds_HideAds AdmobAds_HideAds_wrap
#define AdmobAds_Move AdmobAds_Move_wrap

#endif /* I3D_OS_IPHONE */

void AdmobAdsRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[4];
    funcPtrs[0] = (void*)AdmobAds_InitAds;
    funcPtrs[1] = (void*)AdmobAds_ShowAds;
    funcPtrs[2] = (void*)AdmobAds_HideAds;
    funcPtrs[3] = (void*)AdmobAds_Move;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[4] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("AdmobAds", funcPtrs, sizeof(funcPtrs), flags, AdmobAdsInit, AdmobAdsTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int AdmobAdsStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&AdmobAdsRegisterExt;
    return 0;
}

int g_AdmobAdsVal = AdmobAdsStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    AdmobAdsRegisterExt();
}
#endif

#endif
