/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"

#include "AdmobAds.h"

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*AdmobAds_InitAds_t)(const char* pub_id, int ad_type, int orientation, int x, int y);
typedef  s3eResult(*AdmobAds_ShowAds_t)();
typedef  s3eResult(*AdmobAds_HideAds_t)();
typedef  s3eResult(*AdmobAds_Move_t)(int orientation, int x, int y);

/**
 * struct that gets filled in by AdmobAdsRegister
 */
typedef struct AdmobAdsFuncs
{
    AdmobAds_InitAds_t m_AdmobAds_InitAds;
    AdmobAds_ShowAds_t m_AdmobAds_ShowAds;
    AdmobAds_HideAds_t m_AdmobAds_HideAds;
    AdmobAds_Move_t m_AdmobAds_Move;
} AdmobAdsFuncs;

static AdmobAdsFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0x18b70240, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE, "error loading extension: AdmobAds");
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0x18b70240, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool AdmobAdsAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult AdmobAds_InitAds(const char* pub_id, int ad_type, int orientation, int x, int y)
{
    IwTrace(ADMOBADS_VERBOSE, ("calling AdmobAds[0] func: AdmobAds_InitAds"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_AdmobAds_InitAds(pub_id, ad_type, orientation, x, y);
}

s3eResult AdmobAds_ShowAds()
{
    IwTrace(ADMOBADS_VERBOSE, ("calling AdmobAds[1] func: AdmobAds_ShowAds"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_AdmobAds_ShowAds();
}

s3eResult AdmobAds_HideAds()
{
    IwTrace(ADMOBADS_VERBOSE, ("calling AdmobAds[2] func: AdmobAds_HideAds"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_AdmobAds_HideAds();
}

s3eResult AdmobAds_Move(int orientation, int x, int y)
{
    IwTrace(ADMOBADS_VERBOSE, ("calling AdmobAds[3] func: AdmobAds_Move"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_AdmobAds_Move(orientation, x, y);
}
