/*
 * Copyright (C) 2001-2011 Ideaworks3D Ltd.
 * All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Ideaworks Labs.
 * This file consists of source code released by Ideaworks Labs under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_ADMOBADS_H
#define S3E_EXT_ADMOBADS_H

#include <s3eTypes.h>

typedef enum AdmobAds_AdSize
{

    AdmobAds_GAD_SIZE_320x50  = 1,
    AdmobAds_GAD_SIZE_300x250 = 2,
    AdmobAds_GAD_SIZE_468x60  = 3,
    AdmobAds_GAD_SIZE_728x90  = 4,

} AdmobAds_AdSize;

typedef enum AdmobAds_Orientation
{

    AdmobAds_Orientation_Portrait  = 0,
    AdmobAds_GAD_SIZE_Landscape = 1,
    AdmobAds_GAD_SIZE_PortraitDown  = 2,
    AdmobAds_GAD_SIZE_LandscapeDown  = 3,

} AdmobAds_Orientation;
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Returns S3E_TRUE if the AdmobAds extension is available.
 */
s3eBool AdmobAdsAvailable();

s3eResult AdmobAds_InitAds(const char* pub_id, int ad_type, int orientation, int x, int y);

s3eResult AdmobAds_ShowAds();

s3eResult AdmobAds_HideAds();

s3eResult AdmobAds_Move(int orientation, int x, int y);

S3E_END_C_DECL

#endif /* !S3E_EXT_ADMOBADS_H */
